### ISSUE TITLE
Readme errors and enhancements

### ISSUE THREAD

**Issue by sakshamgurbhele** [Nandani-Paliwal/Nandani-Paliwal#2]
Have a look at the below image

<img width="663" alt="Screenshot 2021-09-30 at 11 16 19 AM" src="https://user-images.githubusercontent.com/64558515/135395435-8453a709-24e4-4085-9c59-7db42479b2b5.png">

**Comment by sakshamgurbhele** [comment]
Lol, link are not working see
<img width="576" alt="Screenshot 2021-09-30 at 11 28 40 AM" src="https://user-images.githubusercontent.com/64558515/135395779-2cf9f11e-4987-46e3-ad14-635664432200.png">
<img width="709" alt="Screenshot 2021-09-30 at 11 28 12 AM" src="https://user-images.githubusercontent.com/64558515/135395790-794b1823-487f-4001-a7ce-92e55eecb773.png">
:

**Comment by Nandani-Paliwal** [comment]
thanks for the mention 
I will change the whole readme !!
this was just a copy paste one😅
